window.COMBOS = [
  { name: "Portal", type: "Sword Stats", value: 1900000, rarity: "Legendary", sequence: "Portal X - Portal Z - TTK X - Sanguine Z - TTK Z - Sanguine C - Sanguine X." },
  { name: " AWK Dough", type: "Fruit Stats", value: 2800000, rarity: "Mythic", sequence: "Dough X - Talon X - CDK X - Dough C - CDK Z - Kabucha X - Dough Z - Dough V - Talon X - Talon Z - Dough X." },
  { name: "Diamond", type: "Fruit Stats", value: 600000, rarity: "Uncommon", sequence: "SGuiatr X - Diamond V - Diamond X - SpikeyTrident X - Diamond C - Godhuman X - Godhuman Z - Godhuman C - Diamon M1 - Diamond Z." },
  { name: "Kitsune", type: "Fruit Stats", value: 8000000, rarity: "Mythic", sequence: "Godhuman C - Yama X - Kitsune X - Kitsune C - Kitsune F - Godhuman Z - Godhuman X." },
  { name: "Empyrean Kitsune", type: "Fruit Stats", value: 16000000, rarity: "Mythic Mutation", sequence: "EKitsune C - EKitsune X - Godhuman X - Godhuman C - EKitsune F - FoxLamp X - FoxLamp Z - EKitsune Z." },
  { name: "AWK Buddha", type: "Sword Stats", value: 1200000, rarity: "Legendary", sequence: "Buddha Z - SGuitar X - DragonTrident X - DragonTrident M1x3 - AWKBuddha V - DragonTalon C - Dragon Talon X." },
  { name: "Dragon West", type: "Fruit Stats", value: 9999998, rarity: "Mythic", sequence: "DragonW V - DragonW X - SpikeyTrident X - Godhuman X - Godhuman Z - Godhuman C - DragonW X - DragonW Z." },
  { name: "Eagle", type: "Fruit Stats", value: 550000, rarity: "Uncommon", sequence: "GravityBlade Z - Sanguine Z - Eagle C - Sanguine C - Eagle X - Eagle Z." },
  { name: "Yeti", type: "Fruit Stats", value: 4999999, rarity: "Mythic", sequence: "GravityBlade Z - Godhuman X - Godhuman Z - Godhuman C - Yeti F - Yeti C - Yeti Z." },
  { name: "Fiend Yeti", type: "Fruit Stats", value: 9999999, rarity: "Mythic Mutation", sequence: "Godhuman C - FYeti F - SpikeyTrident X - Godhuman Z - Godhuman X - FYeti Z - FYeti X." },
  { name: "Gas", type: "Fruit Stats", value: 3200000, rarity: "Mythic", sequence: "Gas Z - Gas X - Gas C - CDK Z - SharkmanKarate X - SharkmanKarate Z - CDK X - SharkmanKarate C." },
  { name: "Bomb", type: "Fruit Stats", value: 80000, rarity: "Common", sequence: "Bomb Z - Bomb X - Godhuman Z - Godhuman C - SpikeyTrident X - Godhuman X - Bomb V." },
  { name: "AWK Ice", type: "Sword Stats", value: 350000, rarity: "Uncommon", sequence: "Sguitar X - Ice V - Cyborg v3 - Ice C - PoleV2 X - PoleV2 Z - Godhuman Z - Godhuman C - Godhuman X." },
  { name: "Rocket", type: "Fruit Stats", value: 5000, rarity: "Common", sequence: "Sguitar Z - Godhuman C - Rocket C - SpikeyTrident Z - SpikeyTrident X - Rocket Z - Godhuman Z - Godhuman X." },
  { name: "Blade", type: "Sword Stats", value: 30000, rarity: "Common", sequence: "Sguitar X - Sanguine C - Blade C - CDK Z - CDK X - Sanguine Z - Sanguine X." },
  { name: "Ghost", type: "Fruit Stats", value: 940000, rarity: "Epic", sequence: "Sguitar X - Ghost V - Ghost X - Ghost Z - Godhuman X - Godhuman C - SpikeTrident X - Ghost C - Godhuman Z." },
  { name: "Love", type: "Fruit Stats", value: 1300000, rarity: "Legendary", sequence: "Love C - Godhuman Z - Godhuman C - SoulCane Z - Love X - Love V - Godhuman X." },
  { name: " AWK Quake", type: "Fruit Stats", value: 1000000, rarity: "Legendary", sequence: "GravityBlade Z - Quake V - Godhuman X - Godhuman Z - Godhuman C - Quake Z." },
  { name: "Control", type: "Fruit Stats", value: 9000000, rarity: "Mythic", sequence: "Control Z - Control X - SpikeyTrident X - Control C - Godhuman Z - Godhuman C - Control F - Godhuman X." },
  { name: "AWK Light", type: "Fruit Stats", value: 650000, rarity: "Epic", sequence: "Sguitar X - Sanguine C - Fox Lamp Z - Light V - Light Z - Sanguine Z - FoxLamp X - Light C - Light X - Light Z." },
  { name: "AWK Magma", type: "Fruit Stats", value: 950000, rarity: "Epic", sequence: "Gravity Blade Z - Magma C - Magma V - Godhuman X - Godhuman Z - Godhuman C - Magma X." },
  { name: "Smoke", type: "Fruit Stats", value: 200000, rarity: "Common", sequence: "Sguitar X - Godhuman C - GravityBlade X - GravityBlade Z - Smoke Z - Smoke X - Godhuman Z - Godhuman X." },
  { name: "Creation", type: "Fruit Stats", value: 1400000, rarity: "Legendary", sequence: "Sguitar X - Gravity Z - Creation C - Creation X - Sanguine Z - Sanguine C - Creation Z - Creation V." },
  { name: "Venom", type: "Fruit Stats", value: 3000000, rarity: "Mythic", sequence: "Sguitar X - Venom C - GravityBlade Z - Venom Z - Venom X - Godhuman X - Godhuman Z - Godhuman C - Venom F." },
  { name: "Trex", type: "Fruit Stats", value: 2700000, rarity: "Mythic", sequence: "Trex X - trex C - Sanguine Z - Sanguine C - Yama X - Sanguine X - Trex Z." },
  { name: "Rubber", type: "Fruit Stats", value: 750000, rarity: "Epic", sequence: "Sguitar X - Godhuman C - Rubber F - SpikeyTrident X - Rubber C - Godhuman X - Godhuman Z - Rubber F - Rubber Z." },
  { name: "Pain", type: "Fruit Stats", value: 2300000, rarity: "Legendary", sequence: "Sguitar X - GravityBlade Z - Pain V - Pain C - Pain Z - SharkmanKarate X - SharkmanKarate C - SharkmanKarate Z." },
  { name: "Blizzard", type: "Fruit Stats", value: 2400000, rarity: "Legendary", sequence: "Sguitar X - Blizzard V - SpikeyTrident X - Blizzard X - Blizzard C - Blizzard Z - Godhuman X - Godhuman Z." },
  { name: "Mammoth", type: "Fruit Stats", value: 2699999, rarity: "Mythic", sequence: "Mammoth C - ElectricClaw C - ElectricClaw Z - SpikeyTrident Z - ElectricClaw X - Mammoth X." },
  { name: "Tiger", type: "Fruit Stats", value: 5000000, rarity: "Mythic", sequence: "Sguitar X - Tiger C - SharkmanKarate Z - SharkmanKarate C - CDK X - Tiger Z - Tiger X - Tiger F." },
  { name: "Werewolf Tiger", type: "Fruit Stats", value: 10000000, rarity: "Mythic Mutation", sequence: "ElectricClaw C - ElectricClaw Z - Yama X - WTiger Z - WTiger X - WTiger C." },
  { name: "East Dragon", type: "Fruit Stats", value: 9999997, rarity: "Mythic", sequence: "GravityBlade Z - EDragon M1x3 - Sanguine Z - Sanguine C - EDragon X - EDragon C - Sanguine X - EDragon Z." },
  { name: " AWK Pheonix", type: "Fruit Stats", value: 1800000, rarity: "Legendary", sequence: "Sguitar X - Pheonix X - SpikeyTrident X - Godhuman Z - Godhuman X - Godhuman C." },
  { name: "Lightning", type: "Fruit Stats", value: 2100000, rarity: "Legendary", sequence: "Lightning X - Lightning C - Lightning C - Godhuman Z - Godhuman C - SharkAnchor X - Godhuman X - Lightning Z." },
  { name: "AWK Spider", type: "Fruit Stats", value: 1500000, rarity: "Legendary", sequence: "Spider X - Spider Z - SharkmanKarate X - SharkmanKarate Z - CDK X - Spider V - SharkmanKarate C - UNWK Spider C." },
  { name: "Spirit", type: "Fruit Stats", value: 3400000, rarity: "Mythic", sequence: "Sguitar X - Spirit C (jump after) - Spirit V (down) - Godhuman X - Godhuman Z - Godhuman C (look up) - Spirit X." },
  { name: "Shadow", type: "Fruit Stats", value: 2900000, rarity: "Mythic", sequence: "Shadow Z - Yama X - Shadow V - Shadow X - DragonTalon X - DragonTalon C." },
  { name: "Gravity", type: "Fruit Stats", value: 2500000, rarity: "Mythic", sequence: "Sguitar X - Gravity X - Godhuman Z - Godhuman C - SharkAnchor X - Gravity C - Gravity V - Godhuman X." },
  { name: "AWK Dark", type: "Fruit Stats", value: 500000, rarity: "Uncommon", sequence: "Sguitar X - SharkmanKarate C - CDK X - CDK Z - Dark X - Dark C - SharkmanKarate X - AcidiumRifle Z - Dark V - Dark Z." },
  { name: "AWK Sand", type: "Fruit Stats", value: 420000, rarity: "Uncommon", sequence: "Sguitar - DragonTrident X - Sand X - UNWK Sand C - Sand V - Godhuman X - Godhuman Z - Godhuman C - Sand Z." },
  { name: "AWK Flame", type: "Fruit Stats", value: 250000, rarity: "Uncommon", sequence: "ElectricClaw C - Flame C - CDK Z - Kabucha X - Flame V - ElectricClaw Z - Flame X." },
  { name: "Spike", type: "Fruit Stats", value: 180000, rarity: "Common", sequence: "Godhuman C - SpikeyTrident X - Spike X - Spike C - Cyborg v3 - Godhuman Z - Kabucha X - Spike V - SpikeyTrident Z - Godhuman X." },
  { name: "Spin", type: "Fruit Stats", value: 7500, rarity: "Common", sequence: "Sguitar X - Spin Z - Godhuman X - Godhuman Z - Godhuman C - SpikeyTrident X - Spin C - Spin X." }
];
